### ISSUE TITLE
Order of Exhibitions

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#75]
<img width="526" alt="Screenshot 2024-01-19 at 15 25 59" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/c9b2519c-e5c9-4038-955a-aa94c9ff5066">

Do we have control over the order of the exhibitions are is it by date? If so can we make it latest at the top? Does that make sense do you think?

**Comment by katjam** [comment]
We do have control. Do you mean you want it by longest ago start date at the top? So that "Mother" then "Polly"? Most recent/ farthest in the future last?

**Comment by stuartleech** [comment]
Yep exactly so the current exhibition is top
