### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#78]
We need to customise the email confirmations for ticket purchases. 

At the moment the email is skewed to be product order based with shipping info etc - As we'll only be selling tickets online initially I can change the email template entirely to cater for this. 

The key issue is that the date selected and the exhibition title isn't pulled through to the email.

@katjam Can you confirm the fields I need to pull in to the email template? Are they metafields or something else, sorry I've totally forgotten!

<img width="701" alt="Screenshot 2024-01-25 at 12 44 49" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/c7f32f77-59ce-454d-a07d-5b5fa93ea245">

**Comment by stuartleech** [comment]
Ah Line item properties!

**Comment by stuartleech** [comment]
Used this code to display all line items in the order: https://gist.github.com/ltakens/0c0c584cfa9c460bb64fc647fa28cfdb



![Image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/eda3d10f-a4df-4bb5-aa9b-5deeec2f812b)


Next: How do I get the date and title of the exhibition to show more prominently

**Comment by katjam** [comment]
Done.
