### ISSUE TITLE
Pay what you can functionality

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#79]
Foundling are introducing Pay What You Like on the first Sunday of each month.

I'm thinking we need a new Metafield called "Pay What You Can Sundays" that lists the sundays that this applies to?

When someone selects one of those Sundays the logic on the page displays different ticketing options which fulfill the pay what you can functionality? 

I think they are suggesting there's fixed options like £1, £5, £10 and then an other box where you can put in any amount you choose but we probably need to talk about what is feasible and has the best UX?

Sunday 7th April
Sunday 5th May
Sunday 2nd June
Sunday 7th July
Sunday 4th August
Sunday 1st September

**Comment by katjam** [comment]
I guess let's look at some UI examples. I've used a slider thing before but not sure if that just over complicates. I can get started without that decision anyway.

**Comment by stuartleech** [comment]
National Gallery Pay What You Can on Friday Nights - What a mess!

<img width="657" alt="Screenshot 2024-02-20 at 16 49 01" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/7ff4e293-499b-45bc-b7ca-6511e7419bb1">

**Comment by katjam** [comment]
Yes, that National Gallery one is tricky to parse. I suppose also the argument for slider might be to get people to donate more.

We might as well start simple as you suggest with a text box that defaults to £5.

**Comment by katjam** [comment]
In terms of the "how many people" will that be a multiplier on the amount, or one flat rate no matter how many are coming?

**Comment by stuartleech** [comment]
This is no longer needed
