### ISSUE TITLE
Add line item with date in DD/MM/YYYY

### ISSUE THREAD

**Issue by katjam** [fm-ticketing/dawn-shopify-theme#82]
Zapier it keeps tossing the date to MM/DD/YYYY but seemingly at random.

I think if we could have a separate line item property that was date of visit: DD/MM/YYY on it's own that would be great. Doesn't need to be displayed anywhere just needs to be included in the line items when ordered and I can pick it up.

**Comment by stuartleech** [comment]
It would be good to action this as the other ramification that hadn't been raised is in reporting. 

They want to be able to report on dates that people are attending but the date is tangled with the exhibition

**Comment by katjam** [comment]
I'll stick this up on staging today. You can merge to live when tested.

**Comment by katjam** [comment]
How's this? 
![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/a3e1d374-da35-49f3-87d7-c3628e2b2727)

**Comment by stuartleech** [comment]
That's great, thank you!

**Comment by stuartleech** [comment]
I've tested this and it looks good to me, how do I merge it to live, sorry!

**Comment by katjam** [comment]
Create a Pull Request from staging to main and merge it.

![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/cfdde734-979c-4197-a9fd-b2dac2be9683)
