### ISSUE TITLE
Should it be possible for the Gift Aid field to be blank?

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#87]
I've been pulling in all the line items to a spreadsheet for reporting purposes and I noticed that some web orders have no value in regards to gift aid which seems weird!

So this order has two tickets and a tip and where it should say TRUE or FALSE in regards to Gift Aid it's blank:

<img width="1658" alt="Screenshot 2024-06-04 at 14 44 54" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/25dfe74b-3b19-4232-9b88-b2d86ddfb312">

I checked the order and you can see again there's no gift aid field here:

<img width="678" alt="Screenshot 2024-06-04 at 14 43 13" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/221d8a4b-0b67-47f1-a5cb-6af3639e848d">

Any ideas?

**Comment by katjam** [comment]
I can take a look. I think maybe there is some logic where we don't send anything if the gift aid part is not relevant.

**Comment by stuartleech** [comment]
Thanks!

That makes sense I think we're going to make it so there's only gift-aidable options but I think in this scenario those two tickets should have been giftaidable

It might also not have helped that the variants have been changed...

**Comment by katjam** [comment]
I better check how it is currently working and then you can tell me how we want it to work?

**Comment by katjam** [comment]
Yes. It looks like we only send a value for that line item if there is giftAidDeclaration. Do you want me to change it to send regardless? I think we thought it might confuse folks if the checkout said "Gift Aid declaration: false" when they'd not been given the option.

**Comment by stuartleech** [comment]
Ah of course I see what we did - we're about the make some amends to the ticket options which will mean they are all gift aid applicable so if we remove the non-gft aid ones do you need to do anything or will that just work because the excluded ones will no longer be there?

**Comment by katjam** [comment]
I think it will just work - but if not, should be quick fix.

**Comment by katjam** [comment]
Closing - we think this works with new set up.
