### ISSUE TITLE
Restrict quantity to prevent groups from booking online

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#88]
> Can we put a cap on number of tickets that can be booked at once to be no more than 7 per person - with some kind of pop up to contact tours for groups of 8+

- [ ] Restrict maximum total tickets to 7
- [ ] If someone tries to add more than 7 tickets in total a message is displayed stating they should contact tours@foundlingmuseum.org.uk to arrange their visit

Text used:
For large groups, please contact tours@foundlingmuseum.org.uk to arrange your visit.

**Comment by katjam** [comment]
When total tickets reaches 7:

- [ ] Disable update basket button
- [ ] display message fixed position
- [ ] disable plus buttons

**Comment by katjam** [comment]
@stuartleech I'm taking a look at this today.

**Comment by katjam** [comment]
@stuartleech My PR has included some gubbins from header with `main` and `staging` being out of sync.

Which of them is correct. As in, can I merge main into staging or should I make my changes on a clean staging branch?

**Comment by katjam** [comment]
I've merged a fix for the manual input that maxes them to total of 7 if they try to type number that brings total to more.
