### ISSUE TITLE
Restart Ticket Selection Implications with Full Shopify Store

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#89]
Foundling are looking to launch their Shopify store in October. 

They've been working on the test site which you can see and use here: https://foundling-test-test.myshopify.com/

The question is the "Restart Ticket Selection" button in the basket necessary, does it impact the function of the wider online store. 

I think we might be able to get rid of it but it would be good to take a look at the functionality and just double check

**Comment by katjam** [comment]
I think you are right, we can get rid of it. People can use the delete function in the basket to get rid of tickets.

Ideally, we might want to show the "restart ticket selection" button only if there are tickets in the basket and when pressed, only clear out general admission products, but that feels risky for a release on Monday.

Do you want to hide with css for now and think about it more next month?

**Comment by stuartleech** [comment]
I've added: 

.underlined-link {
  display: none;
}

But slightly concerned there might be other items with that class?!

**Comment by stuartleech** [comment]
I also noticed on the test site that the footer interferes with the calendar, does that just need a z-index?

![Uploading Screenshot 2024-09-26 at 12.28.16.png…]()

**Comment by katjam** [comment]
> I've added:
> 
> .underlined-link { display: none; }
> 
> But slightly concerned there might be other items with that class?!

Yes. That class is in a quite a few places in the theme. We should target more specifically if we can. I can also remove from the markup if that's easier.

Your image of the footer/calendar didn't post but I assume it's this:
![image](https://github.com/user-attachments/assets/39aa07d7-c2ea-4b40-84c8-f35ce2046bad)

**Comment by katjam** [comment]
We might need to change the position attribute for the calendar or the footer so the footer gets pushed down by it.

**Comment by katjam** [comment]
Closed by hiding 626b2b49342a36af245af1349da83cf131e99034
